
package org.androidtutorials.helloworld.decl;

import android.app.Activity;
import android.os.Bundle;

import org.androidtutorials.helloworld.decl.R;
/**
 * This version of Hello World uses a declarative layout and is functionally
 * identical to the programmatic version. The layout is described in a layout
 * file using XML syntax. It describes the view hierarchy with all necessary
 * layout parameters. Directory <code>res/layout/</code> contains the file
 * <code>main.xml</code>. The Android SDK will use the basename of the file to
 * generate a Java identifier with a unique ID in the so-called <code>R</code>
 * -class. It can be referenced via <code>R.layout.main</code>.
 */
public class HelloWorldActivity extends Activity {

    /** Called when the activity is first created. */
    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        /*
         * The overloaded version of method setContentView() take an ID as a
         * parameter. The ID is referenced via the R-class generated by the
         * Android SDK. The ID is used to local the matching main.xml file whose
         * content is parsed to build up the view hierarchy.
         */
        setContentView(R.layout.main);
    }
}